### ISSUE TITLE
directlink to a page transition

### ISSUE THREAD

**Issue by saotith** [icodebuster/transition.js#17]
Hi,
Thanks for your wonderful work with the transition.js.
One questions i've seen and have had many ask. is there a way to link directly to a specfiic page from outside? I.e Using an #anchor tag or so?
Please let me know would really appreciate it.
Thanks

Sao

**Comment by icodebuster** [comment]
@saotith 
I suppose you mean you need to share a particular page like www.yoursite.com#contact and when someone site that url you need to take them to contact page.

take a look at #14

**Comment by saotith** [comment]
Hi @icodebuster  I tried using this but perhaps i'm using it wrong? Could you eleborate on it?
Thank you again very much for the response.

Sao

**Comment by icodebuster** [comment]
@saotith Could you please elaborate or make a sample project of what you are trying to do.

**Comment by saotith** [comment]
For example i've created this page using transition.js and all the pages are within one single page.
If i want someone to link directly to example the contact page www.yoursite.com/#contact that this will link directly.
I know you reference using url.js but i'm not sure how to use it. do you have an example on how it's impmented?

**Comment by icodebuster** [comment]
Try the following sample it is working but the issue is when changing #id in the url and pressing enter does not result in navigation to the specified page.

```html
<div class="pt-wrapper">
    <div class="pt-trigger-container">
        <button class="pt-trigger" id="home" data-animation="50" data-goto="1">Home</button>
        <button class="pt-trigger" id="about" data-animation="58" data-goto="2">About</button>
        <button class="pt-trigger" id="contact" data-animation="16" data-goto="3">Contact</button>
    </div>

    <!--All Pages-->

    <div class="pt-page pt-page-1">
        <h1><strong>Home</strong></h1>
    </div>
    <div class="pt-page pt-page-2">
        <h1><strong>About</strong></h1>
    </div>
    <div class="pt-page pt-page-3">
        <h1><strong>Contact</strong></h1>
    </div>

</div>
```
In your script tag add this
```javascript
<script src="js/url.js"></script>
<script>
$(document ).ready(function() {
    if (url('#') == 'home') {
        $("#home").trigger("click");
    };
    if (url('#') == 'about') {
        $("#about").trigger("click");
    };
    if (url('#') == 'contact') {
        $("#contact").trigger("click");
    };

    $( "#home" ).click(function() {
        parent.location.hash = "home";
    });
    $( "#about" ).click(function() {
        parent.location.hash = "about";
    });
    $( "#contact" ).click(function() {
        parent.location.hash = "contact";
    });
});
</script>
```

**Comment by saotith** [comment]
Great thanks this worked!

**Comment by saotith** [comment]
Great thanks this worked!
