### ISSUE TITLE
remove page from array

### ISSUE THREAD

**Issue by Maveriko** [icodebuster/transition.js#18]
Ahoj,

first, good job. i like and use your repo.

now the question, title tells it.
it is posible to remove one specific page i.e. pt-page-1 out of the next/prev page array?
in my project i have a 'landing' page with a button (data-goto="2") for navigating to the pt-page2
also i have implemented 2 invisible buttons and script funktions for key, mousewheel and swip scrolling:
> a href="#" id="pageleft" class="pt-trigger" data-animation="5" data-goto="-2"
> a href="#" id="pageright" class="pt-trigger" data-animation="6" data-goto="-1"

>//FUNCTIONS TO NAVIGATE BETWEEN PAGES
>//WITH LEFT AND RIGHT ARROW KEY
>jQuery(function($) {
>	$("body").keydown(function(e) {
>		if(e.keyCode == 37) { // left
>			$("#pageleft").trigger("click");
>		}
>    else if(e.keyCode == 39) { // right
>    	$("#pageright").trigger("click");
>    }
>  });
>});

i want to take out pt-page-1 to use "data-goto -2 and -1" to scroll only through "page-2 to page-7"

page-1
|
v
page-2 <-> page-3 <-> page-4 <-> page-5 <-> page-6 <-> page-7 <-> page-2 <-> page-3 ...

http://inwork.maverik.de/

**Comment by icodebuster** [comment]
@Maveriko 

If I am correct, you need to show the landing page just once to the user, then you may add the following code inside **`onEndAnimationon`** function in transition.js file **(after line number 449)**. 

**Note:** Make sure your landing page div be **`#landing-page`.**

```javascript
if ($currentPage.attr('id') == 'landing-page') {
    $('#landing-page').remove();
    $pageWrapper.data('current', 0);
}
```

After adding
```javascript
function onEndAnimation($pageWrapper, $nextPage, $currentPage) {
// Remove the landing page after the animation is complete.
    if ($currentPage.attr('id') == 'landing-page') {
        $('#landing-page').remove();
        $pageWrapper.data('current', 0);
    }
    resetPage($nextPage, $currentPage);
    $pageWrapper.data('isAnimating', false);
}
```
[Sample Code](https://www.dropbox.com/s/4129oeomw3ommna/TransitionLandingTime.zip?dl=0)
