### ISSUE TITLE
Could You Create A Bower Package for it?

### ISSUE THREAD

**Issue by LoveAndHappiness** [icodebuster/transition.js#19]
Like here:

http://bower.io/docs/creating-packages/

Considered doing it for you, but since you are the author, you should insert the package, don't you think?

**Comment by icodebuster** [comment]
@LoveAndHappiness

Thank you for the bower link. Added transition.js to bower. :thumbsup:

**Comment by LoveAndHappiness** [comment]
Also I am the guy who opened the other issue with multistep forms
