### ISSUE TITLE
Page Transitions for Multi-Step-Form?

### ISSUE THREAD

**Issue by LoveAndHappiness** [icodebuster/transition.js#20]
Hi there,

just wanted to let you know, that it seems that you can't use your library to make a page transition through forms to be able to make a Multi-Step-Form.

At least something like this whould be awesome, because you would revolutionize multi-step forms.

```
    <form action="">
        <div class="pt-wrapper">
            <div class="pt-page pt-page1"></div>
            <div class="pt-page pt-page2"></div>
        </div>
    </form>
```

Do you think there is any way to handle this with your library?

**Comment by fabriciopa** [comment]
Have you tried put the triggers inside the wrapper. I have made some tests and the triggers ONLY work if they are inside the wrapper.

**Comment by icodebuster** [comment]
@LoveAndHappiness 

Have you tried the following structure.
```
    <form action="" class="pt-wrapper">
            <div class="pt-page pt-page1"></div>
            <div class="pt-page pt-page2"></div>
        </div>
    </form>
```

 If you can create a sample project with the issue you are facing then I can look into it.
Also please Star the project repo :)
