### ISSUE TITLE
.pt-trigger only inside .pt-wrapper?

### ISSUE THREAD

**Issue by fabriciopa** [icodebuster/transition.js#21]
Hi! I think your work is amazing! Thanks! But I have an issue: it's very problematic to use the triggers only when they are inside the wrapper. I made some changes and they kind work but I guess you might have something better in mind. Think about a very flexible structure where the triggers might be outsite de wrapper. What do you think?

**Comment by icodebuster** [comment]
@fabriciopa 
I needed to have **parent div** (.pt-wrapper) which contains the **child pages** (.pt-pages) to carry out the operations like last page and other animation stuff.

Could you be more elaborate what issue you are having with the pt-wrapper div?

**Comment by fabriciopa** [comment]
I get the idea of the parent div (.pt-wrapper) and the child pages (.pt-pages). But the triggers (.pt-trigger) only work if they are inside the .pt-wrapper as well. In my case, the triggers are in a separated menu, without the wrapper div, so they don't work. Honestly, I dont see why the .pt-trigger MUST be inside the wrapper div too.

**Comment by icodebuster** [comment]
@fabriciopa 

Can you show me your div structure or a sample project.

**Comment by fabriciopa** [comment]
In you example Demo-Single-Page.html the following structure is shown:
<div class="pt-wrapper">
    <div class="pt-trigger-container">
        <button class="pt-trigger" data-animation="1" data-goto="-1">Go to next page</button>
        <button class="pt-trigger" data-animation="2" data-goto="-2">Go to previous page</button>
        <button class="pt-trigger" data-animation="59-60-61-62-63-64-65-66-67" data-goto="-1">Next page - random anims</button>
        <button class="pt-trigger" data-animation="50-51-52-53-54-55-56-57-58" data-goto="-2">Previous page - random anims</button>
        <button class="pt-trigger" data-animation="50" data-goto="1">Go to page 1</button>
        <button class="pt-trigger" data-animation="51" data-goto="2">Go to page 2</button>
        <button class="pt-trigger" data-animation="52" data-goto="3">Go to page 3</button>
        <button class="pt-trigger" data-animation="53" data-goto="4">Go to page 4</button>
        <button class="pt-trigger" data-animation="58" data-goto="5">Go to page 5</button>
        <button class="pt-trigger" data-animation="59-60-61-62-63-64-65-66-67" data-goto="6">Go to page 6</button>

    </div>
........

</div>

This way works just fine.
Now, if I remove the div with the class pt-trigger-container and put outside the pt-wrapper, in case I wanted to put the trigger in a separated menu, like this:
<div class="pt-trigger-container">
        <button class="pt-trigger" data-animation="1" data-goto="-1">Go to next page</button>
        <button class="pt-trigger" data-animation="2" data-goto="-2">Go to previous page</button>
        <button class="pt-trigger" data-animation="59-60-61-62-63-64-65-66-67" data-goto="-1">Next page - random anims</button>
        <button class="pt-trigger" data-animation="50-51-52-53-54-55-56-57-58" data-goto="-2">Previous page - random anims</button>
        <button class="pt-trigger" data-animation="50" data-goto="1">Go to page 1</button>
        <button class="pt-trigger" data-animation="51" data-goto="2">Go to page 2</button>
        <button class="pt-trigger" data-animation="52" data-goto="3">Go to page 3</button>
        <button class="pt-trigger" data-animation="53" data-goto="4">Go to page 4</button>
        <button class="pt-trigger" data-animation="58" data-goto="5">Go to page 5</button>
        <button class="pt-trigger" data-animation="59-60-61-62-63-64-65-66-67" data-goto="6">Go to page 6</button>

</div>

<div class="pt-wrapper">
    

    

    <div class="pt-page pt-page-1">
        <h1><strong>Page 1</strong></h1>
    </div>
    <div class="pt-page pt-page-2">
        <h1><strong>Page 2</strong></h1>
    </div>
    <div class="pt-page pt-page-3">
        <h1><strong>Page 3</strong></h1>
    </div>
    <div class="pt-page pt-page-4">
        <h1><strong>Page 4</strong></h1>
    </div>
    <div class="pt-page pt-page-5">
        <h1><strong>Page 5</strong></h1>
    </div>
    <div class="pt-page pt-page-6">
        <h1><strong>Page 6</strong></h1>
    </div>

</div>

The triggers stop working.

**Comment by icodebuster** [comment]
@fabriciopa 

I got you issue the main reason why it `pt-trigger` needed to be inside `pt-wrapper` was to support multiple animating divs

just change the code on line number 351 
From
```
var $pageWrapper = $pageTrigger.closest('.pt-trigger-container');
```

To 

```
var $pageWrapper = $('.pt-wrapper');
```
I guess this should fix the issue.
Report back if its working, its been very old code so needed some time to refresh my memory. :)

**Comment by icodebuster** [comment]
@fabriciopa 

If you are making a website using this then can you later on send me the url I will surely add it in the readme section.

**Comment by fabriciopa** [comment]
For that particular case it worked. In my website it didn't. I made some other changes and it kind worked. When it's online I will send it to you. Thanks.

**Comment by icodebuster** [comment]
Did you do any changes to transition.js file. If so can you share it :)

**Comment by ghost** [comment]
@fabriciopa Please share you code with us
