### ISSUE TITLE
Programmatic Transition?

### ISSUE THREAD

**Issue by notflip** [icodebuster/transition.js#22]
Is it possible to have the page transition on the click of a button? Or controlled by Javascript?

**Comment by icodebuster** [comment]
Yes it is possible to control it by JavaScript. Please refer this [link](https://github.com/icodebuster/transition.js/issues/10)

Hope you star the repo :+1:

**Comment by notflip** [comment]
Hi,

Thanks for the response, I will try it although making jQuery click a button is kindoff hacky. Would be nice if there would be a method in the future! Keep up the good work!
