### ISSUE TITLE
More of a feature than issue - Random page

### ISSUE THREAD

**Issue by leoniemann** [icodebuster/transition.js#27]
I am using this demo and it's great! 
Is there a feature which will allow you to link to a set of random pages, I have tried the same format as random animation: 

`<button class="pt-trigger" data-animation="4" data-goto="6-7-10-11-12-13-16-17-18-19">RANDOMISE</button>`

Any help will be appreciated!

**Comment by bom2ne1** [comment]
Hi, 
I don't have time to test this as I'm about to go to bed.
but you could try using jquery's .attr to set 'data-goto' to a randomised number.

so to random between page 1 and 10:
$( "elementselector" ).attr( "data-goto", Math.floor(Math.random() \* 10) + 1 );

If you just add it as is, it'll only run once when it's loaded.
If you want it to random every time it is pressed you'll have to add a way to get a random number every time. Maybe add an onclick to the button that runs it when clicked, or sub in a variable that is randomed somehow lol or some other method.

Apart from that I'm not overly knowledged on this module, so I'm not sure if it can natively do what you ask.

Good luck sir :)
