### ISSUE TITLE
Issues with transitions 54-57

### ISSUE THREAD

**Issue by hsog** [icodebuster/transition.js#30]
Excellent, but original code on codrops works fine for me with all transitions whereas with yours transitions 54-57, and only those, cause the trigger buttons to fade out and then back in. I've searched and cannot see any significant changes that might cause this. I'm on OSX and it is the same in both Firefox and Safari.

**Comment by icodebuster** [comment]
@hsog 
Here is a quick fix.
This is based on the Demo-Single-Page.html from the code.

You need to do the following changes.
Move the `pt-trigger-container` div outside of `pt-wrapper` div

Now it will look like below.

```
<div class="pt-trigger-container">
 ...
 ...
 ...
</div>

<div class="pt-wrapper">
 ...
 ...
 ...
</div>
```

Then in transition.js line 350

Currently its like this

```
var $pageWrapper = $pageTrigger.closest('.pt-wrapper');
```

Change it to

```
var $pageWrapper = $('.pt-wrapper');
```

**Note:**
This will break multiple page transition in a single page.

Hope this fixes it.

**Comment by hsog** [comment]
Wow. Super quick reply, thank you.
Yes, that's sorted it. Not sure I really understand why and doubt I would have tracked it down by myself. I got as far as deleting the page backgrounds which sort of worked but I knew that couldn't be the solution. Thanks again.
