### ISSUE TITLE
Some web pages persist.

### ISSUE THREAD

**Issue by hsog** [icodebuster/transition.js#31]
I am using your code to present web pages. On the pages I've placed iframes. Everything works perfectly with some pages e.g. if I place wikipedia pages into those iframes everything works perfectly, but with others e.g. http://www.bbc.co.uk/news the web page persists and remains visible during later transitions. Somehow the page isn't being completely disposed of.

This can be seen by putting an iframe onto just page4 on your demo and then going to pages one to six. With

<iframe height="100%" width="100%" src="https://en.wikipedia.org/wiki/Existentialism"></iframe>

all is good, but with

<iframe height="100%" width="100%" src="http://www.bbc.co.uk/news"></iframe>

the news page continues to display.

Interestingly if you click on a picture on the wikipedia page then that will also persist.

This seems to particularly affect Safari. However, odd things also happen in Firefox where if you have news.bbc on page4 and wikipedia on all other pages then all works fine except the bbc overides on page1. If you only have the iframe on page 4 and your demo pages for the others the bbc does not overide on page1

**Comment by icodebuster** [comment]
@hsog can you provide a sample for me to look into.

**Comment by hsog** [comment]
The first is just your file with wikipedia placed on page4. All works fine but if you select the image on wikipedia then cycle through the pages you will see the issue.
www.hsogphilosophy.com/cfp/iframeIssue/transitions/wikipediaDEMO.html

The second has wikipedia on each page and bbc news on page4
www.hsogphilosophy.com/cfp/iframeIssue/transitions/bbcDEMO.html

Finally, fwiw, and this isn't your problem, this is what I am eventually aiming for
www.hsogphilosophy.com/cfp/iframeIssue/WebPresenter1/WebPresenter.html
Here I have adapted the code so that the transition is specified as part of the page id. All the buttons work in Safari and continue to work when hidden (as planned). Annoyingly all the hidden buttons continue to work in Firefox except for the show/hide button! If it eventually works I thought someone might take it on as an H5P ( https://h5p.org/node/20320 ) I'm not a programmer so am having to work out each little step as I go but it is fun to see how far I can get.

[iframeIssue.zip](https://github.com/icodebuster/transition.js/files/400365/iframeIssue.zip)

**Comment by hsog** [comment]
@icodebuster 
I still haven't worked out why but I have discovered that in this script the content of the iframe somehow determines whether the visibility of the iframe is respected. In a simple htlm page there is no issue. So, in this script, with the following code,  page3 is hidden as expected but the bbc news still shows up on page2 even though its visibility is explicitly set to hidden. The same applies if the content is set to a wikipedia media file which is what happens when you select one of the images on wikipedia.

```

<div class="pt-page pt-page-2" id="02-chosen-data-animation-20">
<h1><strong>Page 2</strong></h1>
<iframe style="visibility: hidden;"  height="100%" width="100%" src="http://news.bbc.co.uk"></iframe>
    </div>
```

```
<div class="pt-page pt-page-3" id="03-chosen-data-animation-30" >
        <h1><strong>Page 3</strong></h1>
        <iframe style="visibility: hidden;" height="100%" width="100%" src="https://en.wikipedia.org/wiki/Ethics"></iframe>
    </div>

```

**Comment by icodebuster** [comment]
@hsog 
Can you specify with version of the browser you were getting this issue.
I had tried on `Firefox 47.0.1` and `Chrome 53.0.2785.46 beta-m` but could not see any issue

I viewed this url
www.hsogphilosophy.com/cfp/iframeIssue/WebPresenter1/WebPresenter.html

**Comment by hsog** [comment]
@icodebuster 

Thanks for checking but on that link there shouldn't be a noticeable problem because they are all wikipedia pages. (I tracked down the show/hide issue that I mentioned — I was setting and checking background which worked fine in Safari but not in Firefox. Changing it to backgroundColor did the trick.)

The issue with the persistent pages should be seen on
http://www.hsogphilosophy.com/cfp/iframeIssue/transitions/bbcDEMO.html

I'm using OSX 10.11.6

Safari 9.1.2 : Problem very clear if you wait for it to load, go to page four then pages 1 & 2

Firefox 48.0 : Hm. Weird. Until this morning I was using 47.? and there was the problem I mentioned with page4 (bbc news) overwriting the first page. Firefox updated this morning to 48.0 and I can no longer replicate the issue :-)

I am beginning to think this might be (mainly?) a Safari issue rather than a code issue per se. This is a problem for me as my pupils will be viewing on their iPads. The above link is not great on an iPad (or at least mine 8.3 ) because of the way the buttons have been styled but the same problem occurs with bbc news persisting. 

Interestingly, if I take the following code and paste it into

http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe
and view it in Safari I get the same issue.

```
<body>
<iframe style="visibility: hidden;" src="https://en.wikipedia.org/wiki/Philosophy"></iframe>
<iframe style="visibility: hidden;" src="http://news.bbc.co.uk"></iframe>
</body>
```

on an iPad at that site I had to use the following and it took a five or six seconds for the news iframe to appear and then a bit longer before it displayed correctly.

```
<body>

<div style="Height:200px; width:300px; overflow:hidden; visibility:hidden">
<iframe src="https://en.m.wikipedia.org/wiki/Philosophy"></iframe>
</div>

<div style="Height:200px; width:300px; overflow:hidden; visibility:hidden">
<iframe src="http://news.bbc.co.uk"></iframe>
</div>

</body>
```

**Comment by icodebuster** [comment]
Are you getting page persistence on all the animations or is there any specific ones?

All the CSS animations are not 100% supported by all the browsers, since you are targeting iPad users I would suggest you to use those animations which works on iPad Safari.

**Comment by icodebuster** [comment]
@hsog 

I tested on iPad it really sucks :( on Safari.
I then viewed it on Firefox (iPad) that too having the same issue. Only animation 1 and 2 was working fine.

**Comment by hsog** [comment]
@icodebuster 

https://bugs.webkit.org/show_bug.cgi?id=125565

I have just now found reference to this bug. This looks as if it could be somehow related. It does not explain why the iframes work fine with some content but not others though.

**Comment by hsog** [comment]
Just in case anyone else happens upon this thread I thought I'd add the workaround that I have settled on.
In the CSS if you add

```
.pt-page iframe{
    width: 0px;
    height: 0px; 
}

.pt-page-current iframe{
    width: 100%;
    height: 100%; 
}
```

it still tries to display the rogue iframes but gives them zero size. It's not a proper solution but it will do for the time being.

BTW Using the bbc news page to illustrate the problem was not a good idea as the issue comes and goes with that page depending on what it contains. I _think_ the issue comes about when some kind of script is being used in the iframed page to display content. This then results in Safari remembering that page as the iframe and displaying it irrespective of the visibility command.

Thanks again for your help.

**Comment by icodebuster** [comment]
:+1:
