### ISSUE TITLE
pages wrapper

### ISSUE THREAD

**Issue by ghost** [icodebuster/transition.js#33]
I want to wrap the pages with a wrapper but the script doesn't work anymore

![capture](https://cloud.githubusercontent.com/assets/2511956/18295654/239a23fe-749b-11e6-907d-6f5252d7c370.PNG)

any idea ?

**Comment by icodebuster** [comment]
You need to change the following line in the transition.js file

**Before**

```
$('.pt-page').each( function() {
            var $page = $(this);
            $page.data('originalClassList', $page.attr('class'));
});
```

**After**
Just added **'.pages-wrapper > .pt-page'**

```
$('.pages-wrapper > .pt-page').each( function() {
            var $page = $(this);
            $page.data('originalClassList', $page.attr('class'));
});
```

Extremely sorry for the delayed response.
