### ISSUE TITLE
Wordpress integration

### ISSUE THREAD

**Issue by mojpe** [icodebuster/transition.js#35]
I'm not sure if I'm asking in right place but I was trying to implement to wordpress but it seems that I had trouble imlementing it like the id's for anchor are not read at all. 
Any suggestions how to do it or best prctice?

Thank you in advance

**Comment by icodebuster** [comment]
@mojpe Could you please me your html code, or the DOM structure.

**Comment by icodebuster** [comment]
Closing the question due to no response.
