### ISSUE TITLE
Not able to make the transition effect work

### ISSUE THREAD

**Issue by etiennedesign** [icodebuster/transition.js#37]
Hi,
I am trying to integrate the page transition to my test site but i can't make it work.
This is the github page: https://etiennedesign.github.io/2d-web-experience/

And this is the project: https://github.com/etiennedesign/2d-web-experience

The idea is to have a move transition when you click on the white arrows.
I'm not a dev so i am probably doing something wrong here.
Every help or advice would be very appreciated :)

**Comment by icodebuster** [comment]
@etiennedesign 
This library works with single page website, as per your code you have separate HTML pages, you need to club everything into a single page.
