### ISSUE TITLE
Transition.js : Invalid 'data-goto' attribute configuration

### ISSUE THREAD

**Issue by istiyakamin** [icodebuster/transition.js#38]
error:: 
 Transition.js : Invalid 'data-goto' attribute configuration

how can I solve this

**Comment by icodebuster** [comment]
@istiyakaminsanto 
Can you share your HTML code

**Comment by mojpe** [comment]
Can you share the code or if you share what is console error?

**Comment by ghost** [comment]
I am also having this issue. The Console does not report errors regarding it... Everything else works well, only this does not.

**Comment by icodebuster** [comment]
@Dejan31 can you share the code with the `data-goto` attribute.

You need to specify the `data-goto` and `data-animation` attribute to the element with the class `pt-trigger`
